package = "default-lapis-app"
version = "dev-1"
source = {
   url = "*** please add URL for source tarball, zip or repository here ***"
}
description = {
   summary = "This the default lapis project generated by `lapis new`.",
   detailed = "This the default lapis project generated by `lapis new`. My main intention was to have a nice Dockerfile for developing other lapis projects in the future.",
   homepage = "*** please enter a project homepage ***",
   license = "*** please specify a license ***"
}
build = {
   type = "builtin",
   modules = {
      app = "app.lua",
      config = "config.lua",
      models = "models.lua"
   }
}
